spring:
  profiles:
    active: test
    
---   
    
server:
  port: 5800
spring:
  profiles: dev #声明配置的类型
  application:
    name: config-client-dev
  
---

server:
  port: 5800
spring:
  profiles: test #声明配置的类型
  application:
    name: config-client-test
