spring:
  profiles:
    active: test
    
---

server:
  port: 8080
spring:
  application:
    name: cloud-dev2
  profiles:
    active: dev
    
---

server:
  port: 8090
spring:
  application:
    name: cloud-test2
  profiles:
    active: test
